### PR TITLE
feat: nix support

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
so anyone can build installing just nix.

and i can "mount" mumps into ipopt instead of hsl

### CODE REVIEW

**Comment by scivision** [comment]
Thanks I wonder if this might work even better in its own repository i.e. yours, as this one is focused on CMake and the two build systems might be out of sync or maintenance if combined.

**Comment by dzmitry-lahoda** [comment]
final state of mumps is like https://github.com/scipopt/scip or https://github.com/oneapi-src/oneTBB .

mumps in git and all build systems in same repo.

**Comment by dzmitry-lahoda** [comment]
only one build system is maintained and in sync 100% of changes - that which runs on ci as merge gate, others best effort.

**Comment by dzmitry-lahoda** [comment]
nix can read these:

```
    mumps-src = {
      url = "https://mumps-solver.org/MUMPS_5.6.2.tar.gz";
      flake = false;
    };

 "-D MUMPS_UPSTREAM_VERSION=5.6.2"

```

from cmake/json files to reduce brittelness easy

**Comment by dmikushin** [comment]
@dzmitry-lahoda , thank you for working on this! Alas, not so many people know what the NixOS is yet.

**Comment by dzmitry-lahoda** [comment]
I was working. I was able to assemble from lowest level to SCIP NLP. Stuck on compling Python wrapper on SCIP. 

In general experience was good. I could assemble any parameters as I wished too accross whole stack (like double support). 

Hope people will be more aware of this sure.

**Comment by dzmitry-lahoda** [comment]
> CMake and the two build systems might be out of sync or maintenance if combined.

@scivision Nix is using CMake, it is not separate build system. They could be, but if Nix well written they will not, and if will - nix person will send PR.

**Comment by dzmitry-lahoda** [comment]
closing for now. may be next time.

**Pull request closed without merging**
